services:
  postgres:
    image: postgres:latest
    container_name: restaurantContainer
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    restart: always